<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="3" ignored="4" total="16" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="All Test Suite" duration-ms="36855" started-at="2020-05-28T22:09:00 IST" finished-at="2020-05-28T22:09:37 IST">
    <groups>
    </groups>
    <test name="XYZ BANK" duration-ms="26812" started-at="2020-05-28T22:09:00 IST" finished-at="2020-05-28T22:09:27 IST">
      <class name="com.infy.practice.testcases.OpenAccountFunctionality">
        <test-method status="PASS" signature="PageObjectsInitialization()[pri:0, instance:com.infy.practice.testcases.OpenAccountFunctionality@cb0ed20]" name="PageObjectsInitialization" is-config="true" duration-ms="6" started-at="2020-05-28T22:09:07 IST" finished-at="2020-05-28T22:09:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PageObjectsInitialization -->
        <test-method status="PASS" signature="Create_New_Customer_Open_A_Dollar_Account_And_Verify()[pri:0, instance:com.infy.practice.testcases.OpenAccountFunctionality@cb0ed20]" name="Create_New_Customer_Open_A_Dollar_Account_And_Verify" duration-ms="2917" started-at="2020-05-28T22:09:07 IST" finished-at="2020-05-28T22:09:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Create_New_Customer_Open_A_Dollar_Account_And_Verify -->
        <test-method status="PASS" signature="Create_New_Customer_Open_A_Pound_Account_And_Verify()[pri:0, instance:com.infy.practice.testcases.OpenAccountFunctionality@cb0ed20]" name="Create_New_Customer_Open_A_Pound_Account_And_Verify" duration-ms="2793" started-at="2020-05-28T22:09:11 IST" finished-at="2020-05-28T22:09:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Create_New_Customer_Open_A_Pound_Account_And_Verify -->
        <test-method status="SKIP" signature="Create_New_Customer_Open_A_Rupee_Account_And_Verify()[pri:0, instance:com.infy.practice.testcases.OpenAccountFunctionality@cb0ed20]" name="Create_New_Customer_Open_A_Rupee_Account_And_Verify" duration-ms="37" started-at="2020-05-28T22:09:13 IST" finished-at="2020-05-28T22:09:13 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Create_New_Customer_Open_A_Rupee_Account_And_Verify is set as 'N' for Run Mode]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Create_New_Customer_Open_A_Rupee_Account_And_Verify is set as 'N' for Run Mode
at com.infy.practice.listeners.CustomListeners.onTestStart(CustomListeners.java:20)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:73)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Create_New_Customer_Open_A_Rupee_Account_And_Verify -->
      </class> <!-- com.infy.practice.testcases.OpenAccountFunctionality -->
      <class name="com.infy.practice.testcases.DepositWithdrawFunctionality">
        <test-method status="PASS" signature="PageObjectsInitialization()[pri:0, instance:com.infy.practice.testcases.DepositWithdrawFunctionality@8e24743]" name="PageObjectsInitialization" is-config="true" duration-ms="8" started-at="2020-05-28T22:09:14 IST" finished-at="2020-05-28T22:09:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PageObjectsInitialization -->
        <test-method status="PASS" signature="Verify_Initial_Account_Balance()[pri:0, instance:com.infy.practice.testcases.DepositWithdrawFunctionality@8e24743]" name="Verify_Initial_Account_Balance" duration-ms="992" started-at="2020-05-28T22:09:14 IST" finished-at="2020-05-28T22:09:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Initial_Account_Balance -->
        <test-method status="PASS" signature="Deposit_Amount_And_Verify()[pri:0, instance:com.infy.practice.testcases.DepositWithdrawFunctionality@8e24743]" name="Deposit_Amount_And_Verify" duration-ms="604" started-at="2020-05-28T22:09:15 IST" depends-on-methods="com.infy.practice.testcases.DepositWithdrawFunctionality.Verify_Initial_Account_Balance" finished-at="2020-05-28T22:09:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Deposit_Amount_And_Verify -->
        <test-method status="PASS" signature="Withdraw_Amount_And_Verify()[pri:0, instance:com.infy.practice.testcases.DepositWithdrawFunctionality@8e24743]" name="Withdraw_Amount_And_Verify" duration-ms="636" started-at="2020-05-28T22:09:15 IST" depends-on-methods="com.infy.practice.testcases.DepositWithdrawFunctionality.Deposit_Amount_And_Verify" finished-at="2020-05-28T22:09:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Withdraw_Amount_And_Verify -->
        <test-method status="FAIL" signature="Withdraw_Amount_More_Than_Balance()[pri:0, instance:com.infy.practice.testcases.DepositWithdrawFunctionality@8e24743]" name="Withdraw_Amount_More_Than_Balance" duration-ms="10597" started-at="2020-05-28T22:09:16 IST" depends-on-methods="com.infy.practice.testcases.DepositWithdrawFunctionality.Withdraw_Amount_And_Verify" finished-at="2020-05-28T22:09:27 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [500] but found [600]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [500] but found [600]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.infy.practice.pageobjects.UserHomePage.verifyAmountAfterWithdrawFailure(UserHomePage.java:135)
at com.infy.practice.testcases.DepositWithdrawFunctionality.Withdraw_Amount_More_Than_Balance(DepositWithdrawFunctionality.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Withdraw_Amount_More_Than_Balance -->
      </class> <!-- com.infy.practice.testcases.DepositWithdrawFunctionality -->
      <class name="com.infy.practice.testcases.CreateDeleteCustFunctionality">
        <test-method status="PASS" signature="PageObjectsInitialization()[pri:0, instance:com.infy.practice.testcases.CreateDeleteCustFunctionality@5891e32e]" name="PageObjectsInitialization" is-config="true" duration-ms="46" started-at="2020-05-28T22:09:00 IST" finished-at="2020-05-28T22:09:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PageObjectsInitialization -->
        <test-method status="PASS" signature="Create_New_Customer()[pri:1, instance:com.infy.practice.testcases.CreateDeleteCustFunctionality@5891e32e]" name="Create_New_Customer" duration-ms="2421" started-at="2020-05-28T22:09:00 IST" finished-at="2020-05-28T22:09:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Create_New_Customer -->
        <test-method status="FAIL" signature="Verify_Newly_Created_Customer_In_Customer_Table()[pri:2, instance:com.infy.practice.testcases.CreateDeleteCustFunctionality@5891e32e]" name="Verify_Newly_Created_Customer_In_Customer_Table" duration-ms="1332" started-at="2020-05-28T22:09:03 IST" depends-on-methods="com.infy.practice.testcases.CreateDeleteCustFunctionality.Create_New_Customer" finished-at="2020-05-28T22:09:05 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [560101] but found [560100]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [560101] but found [560100]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.infy.practice.pageobjects.CustomersTable.verifyNewCustomerPresentInsideCustomerTable(CustomersTable.java:48)
at com.infy.practice.testcases.CreateDeleteCustFunctionality.Verify_Newly_Created_Customer_In_Customer_Table(CreateDeleteCustFunctionality.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Newly_Created_Customer_In_Customer_Table -->
        <test-method status="FAIL" signature="Delete_Newly_Created_Customer()[pri:3, instance:com.infy.practice.testcases.CreateDeleteCustFunctionality@5891e32e]" name="Delete_Newly_Created_Customer" duration-ms="1867" started-at="2020-05-28T22:09:05 IST" depends-on-methods="com.infy.practice.testcases.CreateDeleteCustFunctionality.Create_New_Customer" finished-at="2020-05-28T22:09:07 IST">
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[element click intercepted: Element <button ng-click="deleteCust(cust)">...</button> is not clickable at point (552, 496). Other element would receive the click: <iframe frameborder="0" style="background-color: transparent; vertical-align: text-bottom; position: relative; width: 100%; height: 100%; min-width: 100%; min-height: 100%; max-width: 100%; max-height: 100%; margin: 0px; overflow: hidden; display: block;" src="about:blank" data-test-id="ChatWidgetWindow-iframe" title="Zendesk Chat widget window"></iframe>
  (Session info: headless chrome=83.0.4103.61)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-4SC5RBR', ip: '192.168.1.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.61, chrome: {chromedriverVersion: 83.0.4103.14 (be04594a2b841..., userDataDir: C:\Users\sayan\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:56108}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: f46a0f8b39483ffa17a289f9333ad462]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <button ng-click="deleteCust(cust)">...</button> is not clickable at point (552, 496). Other element would receive the click: <iframe frameborder="0" style="background-color: transparent; vertical-align: text-bottom; position: relative; width: 100%; height: 100%; min-width: 100%; min-height: 100%; max-width: 100%; max-height: 100%; margin: 0px; overflow: hidden; display: block;" src="about:blank" data-test-id="ChatWidgetWindow-iframe" title="Zendesk Chat widget window"></iframe>
  (Session info: headless chrome=83.0.4103.61)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-4SC5RBR', ip: '192.168.1.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.61, chrome: {chromedriverVersion: 83.0.4103.14 (be04594a2b841..., userDataDir: C:\Users\sayan\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:56108}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: f46a0f8b39483ffa17a289f9333ad462
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at com.infy.practice.pageobjects.CustomersTable.deleteCustomerAndVerify(CustomersTable.java:83)
at com.infy.practice.testcases.CreateDeleteCustFunctionality.Delete_Newly_Created_Customer(CreateDeleteCustFunctionality.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Delete_Newly_Created_Customer -->
      </class> <!-- com.infy.practice.testcases.CreateDeleteCustFunctionality -->
    </test> <!-- XYZ BANK -->
    <test name="Different Actions on window" duration-ms="9972" started-at="2020-05-28T22:09:27 IST" finished-at="2020-05-28T22:09:37 IST">
      <class name="com.infy.practice.testcases.DifferentActions">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.infy.practice.testcases.DifferentActions@704d6e83]" name="setUp" is-config="true" duration-ms="7990" started-at="2020-05-28T22:08:52 IST" finished-at="2020-05-28T22:09:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Upload_File_Using_Send_Keys()[pri:0, instance:com.infy.practice.testcases.DifferentActions@704d6e83]" name="Upload_File_Using_Send_Keys" duration-ms="4443" started-at="2020-05-28T22:09:27 IST" finished-at="2020-05-28T22:09:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Upload_File_Using_Send_Keys -->
        <test-method status="PASS" signature="Window_Authorization()[pri:0, instance:com.infy.practice.testcases.DifferentActions@704d6e83]" name="Window_Authorization" duration-ms="5195" started-at="2020-05-28T22:09:32 IST" finished-at="2020-05-28T22:09:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Window_Authorization -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.infy.practice.testcases.DifferentActions@704d6e83]" name="tearDown" is-config="true" duration-ms="942" started-at="2020-05-28T22:09:37 IST" finished-at="2020-05-28T22:09:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.infy.practice.testcases.DifferentActions -->
    </test> <!-- Different Actions on window -->
  </suite> <!-- All Test Suite -->
</testng-results>
